bokoboshahni/eve-indy-watch

.github/workflows/codeql-analysis.yml
=> chore: set up codeql

.github/workflows/build.yml
=> chore: rename cicd workflow to build

app/services/concerns/service_helpers.rb, app/services/location/snapshot_orders_from_esi.rb, app/services/market/calculate_type_statistics.rb, app/services/market/calculate_type_statistics_queuer.rb, app/services/market/persist_type_statistics.rb, app/workers/location/snapshot_orders_from_esi_worker.rb
=> chore: only log final metrics

app/models/contract.rb, app/services/contract/sync_from_esi.rb, app/services/contract/sync_items_from_esi.rb, db/migrate/20220113151030_change_nullable_on_contract_assignee.rb, db/structure.sql, spec/models/contract_spec.rb
=> fix: allow nil assignee for public contracts

app/views/admin/markets/_markets.html.erb
=> feat: visual indicator of market sync healthiness

app/controllers/application_controller.rb, app/views/application/_side_nav.html.erb
=> feat: show app version in side nav

app/controllers/procurement_orders_controller.rb, app/views/procurement_orders/_item_form.html.erb, app/views/procurement_orders/_order_form.html.erb, app/views/procurement_orders/show.html.erb
=> fix: procurement order ui fixes

app/views/procurement_orders/show.html.erb
=> fix: use alliance procurement order requester

app/components/order_controller.js
=> fix: double isk

app/components/order_item_controller.js, app/controllers/application_controller.rb, app/controllers/procurement_orders_controller.rb, app/models/procurement_order.rb, app/policies/procurement_order_policy.rb, app/views/application/_mobile_nav.html.erb, app/views/application/_side_nav.html.erb, app/views/procurement_orders/_order_fields.html.erb
- fix: force two decimal places
- fix: guard against nil bonus and multiplier
- feat: move procurement nav item up
- fix: move order item template
the changes.
=> fix: procurement order ui tweaks

app/models/corporation.rb, app/views/admin/markets/_markets.html.erb, config/deploy.rb, lib/tasks/sde.rake
- fix: available_esi_authorizations query
- chore: rename sde:load to sde:import
- fix: allow for markets that haven't run yet
the changes.
=> misc fixes

app/workers/market/calculate_type_statistics_worker.rb
=> chore: stop persisting type stats to timescaledb

Procfile.dev, app/controllers/procurement_orders_controller.rb, app/models/procurement_order.rb, app/policies/procurement_order_policy.rb, app/views/procurement_orders/_order_fields.html.erb, app/views/procurement_orders/_order_summary.html.erb, app/views/procurement_orders/_orders.html.erb, app/views/procurement_orders/list_items_card.html.erb, config/routes.rb, db/migrate/20220113222032_add_visibility_to_procurement_orders.rb, db/statistics_structure.sql, db/structure.sql, spec/models/procurement_order_spec.rb
=> feat: add visibility to procurement orders

app/services/contract/sync_items_from_esi.rb
=> fix: remove bad api call

app/models/ahoy/event.rb, app/models/ahoy/visit.rb, db/migrate/20220116024530_create_ahoy_tables.rb, db/structure.sql
=> feat: move ahoy to primary db

app/models/ahoy/event.rb, app/models/ahoy/visit.rb, app/models/region.rb, app/models/region_type_history.rb, app/models/type.rb, app/services/region/import_type_history.rb, db/migrate/20220116032254_create_region_type_histories.rb, db/structure.sql, spec/models/region_type_history_spec.rb
=> feat: move region type histories to primary db

app/models/report_run.rb, app/models/user.rb, app/reports/application_report.rb, db/migrate/20220116033406_create_report_runs.rb, db/structure.sql, spec/models/report_run_spec.rb
=> feat: move report runs to primary db

Dockerfile.dev, config/initializers/sidekiq.rb, config/puma.rb, docker-compose.yml
=> feat: docker-compose dev environment

app/services/location/snapshot_orders_from_esi.rb, app/services/market/calculate_type_statistics.rb
=> fix: ensure all snapshot keys are expired

app/services/sde/load_stations.rb
=> fix: load stations from moons properly

docker-compose.yml
=> fix: link webpack correctly in docker-compose environments

.pryrc, DEVELOPMENT.md, lib/tasks/data.rake
- fix: link webpack correctly in docker-compose environments
- feat: redirect to previous url on sso login
- docs: stub for development workflow
- chore: add data task to create jita market
- fix: remove database loads from pryrc
the changes.
=> feat: onboarding

Dockerfile.dev, Gemfile.lock, bin/setup, docker-compose.yml
=> feat: more robust docker-compose environment

app/views/procurement_orders/show.html.erb
=> fix: breadcrumb label

Dockerfile.dev
=> feat: add bash to dev containers

.pryrc, DEVELOPMENT.md, app/models/region.rb, app/models/structure.rb
=> docs: add instructions for creating alliance market

tailwind.config.js
=> chore: enable all tailwind colors

.pryrc, DEVELOPMENT.md
=> docs: document esi usage in console

app/models/alliance.rb, app/models/application_record.rb
=> chore: ensure #log_name works on any model

config/environments/development.rb
=> fix: web console from docker environment

app/components/order_controller.js, app/components/order_item_controller.js, app/controllers/procurement_orders_controller.rb, app/javascript/controllers/index.js, app/models/procurement_order.rb, app/policies/procurement_order_policy.rb, app/views/procurement_orders/_accept_modal.html.erb, app/views/procurement_orders/_cancel_modal.html.erb, app/views/procurement_orders/_delete_modal.html.erb, app/views/procurement_orders/_deliver_modal.html.erb, app/views/procurement_orders/_item_form.html.erb, app/views/procurement_orders/_new_item.html.erb, app/views/procurement_orders/_order_fields.html.erb, app/views/procurement_orders/_order_form.html.erb, app/views/procurement_orders/_order_summary_items.html.erb, app/views/procurement_orders/_orders_dashboard_table.html.erb, app/views/procurement_orders/_orders_history.html.erb, app/views/procurement_orders/_redraft_modal.html.erb, app/views/procurement_orders/_release_modal.html.erb, app/views/procurement_orders/_undeliver_modal.html.erb, app/views/procurement_orders/history.html.erb, app/views/procurement_orders/index.html.erb, app/views/procurement_orders/show.html.erb, app/workers/location/snapshot_orders_from_esi_worker.rb, config/routes.rb, package.json, yarn.lock
=> Procurement order fixes and enhancements

app/models/procurement_order_item.rb, app/views/procurement_orders/_order_fields.html.erb, app/views/procurement_orders/_order_summary_info.html.erb, app/views/procurement_orders/_order_summary_items.html.erb
=> feat: hide multiplier from supplier views

app/views/procurement_orders/_order_fields.html.erb
=> fix: erb error

app/views/procurement_orders/_accept_modal.html.erb, app/views/procurement_orders/_cancel_modal.html.erb, app/views/procurement_orders/_delete_modal.html.erb, app/views/procurement_orders/_deliver_modal.html.erb, app/views/procurement_orders/_orders_dashboard_table.html.erb, app/views/procurement_orders/_receive_modal.html.erb, app/views/procurement_orders/_redraft_modal.html.erb, app/views/procurement_orders/_release_modal.html.erb, app/views/procurement_orders/_undeliver_modal.html.erb, app/views/procurement_orders/history.html.erb
=> feat: orders dashboard enhancements

.env.example, DEVELOPMENT.md, Dockerfile.dev, app/models/structure.rb, app/services/sde/load_constellations.rb, app/services/sde/load_regions.rb, app/services/sde/load_solar_systems.rb, app/services/sde/load_stations.rb, app/services/sde/yaml_loader.rb, bin/setup, dip.yml, docker-compose.yml, lib/tasks/bootstrap.rake, lib/tasks/data.rake
=> feat: update dev bootstrapping

Gemfile, Gemfile.lock, app/controllers/procurement_orders_controller.rb, app/helpers/procurement_orders_helper.rb, app/models/procurement_order.rb, app/policies/procurement_order_policy.rb, app/views/procurement_orders/_orders_dashboard_table.html.erb, app/views/procurement_orders/show.html.erb, db/migrate/20220118173454_add_unconfirmed_to_procurement_order_status.rb, db/migrate/20220118175551_add_unconfirmed_at_to_procurement_orders.rb, db/structure.sql, spec/models/procurement_order_spec.rb
=> feat: state machine for procurement orders

app/javascript/controllers/index.js, app/models/procurement_order.rb, app/views/procurement_orders/_order_summary_info.html.erb, app/views/procurement_orders/show.html.erb, package.json, yarn.lock
- feat: state machine for procurement orders
- feat: copy order items to multibuy
- feat: add market value
the changes.
=> feat: multibuy items and market value

app/controllers/procurement_orders_controller.rb, app/views/layouts/application.html.erb, app/views/procurement_orders/_accept_modal.html.erb, app/views/procurement_orders/_order_fields.html.erb, app/views/procurement_orders/_order_summary_info.html.erb, app/views/procurement_orders/_orders_dashboard_table.html.erb, app/views/procurement_orders/show.html.erb
=> feat: estimated and target completion dates

app/workers/contract/discover_fittings_worker.rb, app/workers/contract/sync_from_esi_worker.rb, app/workers/contract/sync_items_from_esi_worker.rb, app/workers/corporation/fetch_contracts_from_esi_worker.rb, app/workers/corporation/sync_all_contracts_from_esi_worker.rb, app/workers/market/calculate_type_statistics_worker.rb, app/workers/market/ingest_all_worker.rb, config/sidekiq.yml, docker-compose.yml
=> chore: separate queues for contracts and markets

docker-compose.yml
=> chore: postgres container healthcheck

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, Procfile.dev
=> feat: devcontainer configuration for vscode

app/services/market/calculate_type_statistics.rb
=> chore: clean up logging

app/models/user.rb, config/application.rb
=> feat: default roles configuration

.devcontainer/devcontainer.json, Procfile.dev, api/openapi.yml, app/controllers/api/me_controller.rb, app/controllers/api/root_controller.rb, app/controllers/api_controller.rb, app/views/api/me/show.json.jbuilder, config/application.rb, package.json, yarn.lock
=> feat: authenticated user api endpoint

.devcontainer/Dockerfile
=> chore: use postgresql 14 and redis 6

app/controllers/application_controller.rb, app/models/character.rb, app/models/corporation.rb, app/models/procurement_order.rb, app/views/procurement_orders/_accept_modal.html.erb, app/views/procurement_orders/_deliver_modal.html.erb, app/views/procurement_orders/_order_fields.html.erb, app/views/procurement_orders/_order_summary_info.html.erb, app/views/procurement_orders/show.html.erb, config/initializers/rate_limiting.rb, db/migrate/20220122162604_add_procurement_order_requester_to_corporations.rb, db/structure.sql, spec/models/corporation_spec.rb
=> feat: corporation procurement order assignee

app/services/location/snapshot_orders_from_esi.rb, app/services/market/archive_type_statistics.rb, app/services/market/calculate_type_statistics.rb, app/services/market/calculate_type_statistics_callback.rb, app/services/market/calculate_type_statistics_queuer.rb
=> feat: archive type stats to history bucket

Procfile.dev, app/services/market/calculate_type_statistics_callback.rb, app/workers/market/archive_type_statistics_worker.rb, config/sidekiq.yml
=> feat: archive markets asynchronously

app/models/market.rb, app/services/market/calculate_type_statistics_callback.rb, db/migrate/20220125211045_add_archiving_enabled_to_markets.rb, db/structure.sql, spec/models/market_spec.rb
=> feat: flag to enable/disable market archiving

app/models/group.rb, app/models/killmail.rb, app/models/killmail_attacker.rb, app/models/killmail_item.rb, app/models/type.rb, app/services/group/sync_from_esi.rb, app/services/killmail/import_from_esi.rb, app/services/type/sync_from_esi.rb, db/migrate/20220125212154_add_esi_columns_to_types.rb, db/migrate/20220125213027_remove_foreign_key_for_killmail_types.rb, db/migrate/20220125222823_add_esi_columns_to_groups.rb, db/structure.sql, spec/models/group_spec.rb, spec/models/killmail_attacker_spec.rb, spec/models/killmail_item_spec.rb, spec/models/killmail_spec.rb, spec/models/type_spec.rb
=> fix: fallback to esi for killmail types

app/services/killmail/import_from_esi.rb
=> fix: return existing killmail

app/services/market/calculate_type_statistics_callback.rb
=> fix: archiving enablement conditional

app/workers/contract/sync_items_from_esi_worker.rb
=> fix: use contracts queue

DEVELOPMENT.md, lib/tasks/bootstrap.rake
=> docs: reference correct env variable for admin character ids

.rubocop.yml, app/policies/procurement_order_policy.rb, spec/factories/categories.rb, spec/factories/constellations.rb, spec/factories/groups.rb, spec/factories/locations.rb, spec/factories/procurement_order_items.rb, spec/factories/procurement_orders.rb, spec/factories/regions.rb, spec/factories/solar_systems.rb, spec/factories/stations.rb, spec/factories/types.rb, spec/policies/procurement_order_policy_spec.rb
=> fix: visibility for user-requested orders

Gemfile, Gemfile.lock, spec/rails_helper.rb, spec/requests/esi_authorizations_spec.rb, spec/requests/home_spec.rb, spec/support/helpers/sso_helpers.rb
=> test: request spec for homepage

app/components/paginator_component.html.erb
=> fix: use rails helpers for pagination links

app/views/procurement_orders/show.html.erb
=> fix: target completion due date alert

app/views/procurement_orders/show.html.erb
=> fix: target completion due date supplier alert

Capfile, Gemfile, Gemfile.lock
=> chore: task to start rails console from capistrano

.devcontainer/Dockerfile, .github/workflows/build.yml, .vscode/tasks.json, Gemfile, Gemfile.lock, app/components/character_portrait_component.rb, app/controllers/test_logins_controller.rb, app/models/market.rb, app/views/application/_top_nav.html.erb, app/views/test_logins/show.html.erb, bin/ci-features, config/routes.rb, spec/factories/procurement_orders.rb, spec/rails_helper.rb, spec/support/headless.rb, spec/support/helpers/request_helpers.rb, spec/support/helpers/system_helpers.rb, spec/system/procurement_orders/show_spec.rb
- Adds a test harness for Capybara + Selenium + Chrome for system tests
- Adds a basic system test for procurement order details
the changes.
=> test: add system test for order details

app/models/esi_authorization.rb, app/models/slack_webhook.rb, app/services/resolve_and_sync_entity.rb
=> fix: resolve additional character ids

app/services/location/snapshot_orders_from_esi.rb, app/services/market/calculate_type_statistics.rb, app/views/admin/structures/show.html.erb, app/views/home/index.html.erb
=> fix: path to login button image

.gitignore, .tool-versions, Gemfile.lock
- chore: add vendor/bundle to gitignore
- chore: update gemfile.lock for darwin
- chore: add .tool-versions for asdf
the changes.
=> Chores for macOS

app/services/structure/sync_from_esi.rb
=> fix: don't set expires or last modified for unknown structures

app/controllers/application_controller.rb, app/controllers/procurement_orders_controller.rb, app/views/procurement_orders/_order_fields.html.erb
- chore: use Pundit::Authorization
- fix: only use default location if set
the changes.
=> fix: only use default location if set

Gemfile
=> fix: allow newer patch versions of ruby 3.0

config/webpacker.yml, package.json, yarn.lock
=> chore: ensure shakapacker version matches between bundler and yarn

app/views/procurement_orders/_orders_dashboard_table.html.erb, app/views/procurement_orders/index.html.erb
=> feat: add tracking number to unconfirmed orders table

app/views/procurement_orders/show.html.erb
=> feat: add tracking number to detail view
